## hibernate

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

## SETTING PROFILE PRODUCTION
spring:
  profiles:
    active: production
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

---
## SETTING PROFILE DEV
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234

---

## SETTING LOG
logging:
  level:
    root: debug
